import AppKit
import AintoCore

/// Monitors the system clipboard for changes every 500ms.
/// Reference: Maccy/Raycast poll NSPasteboard.general.changeCount.
@MainActor
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    var onClipboardChanged: (() -> Void)?

    /// Pasteboard types that indicate sensitive/transient data (should be skipped).
    private static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    func startMonitoring() {
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func checkClipboard() {
        let currentCount = NSPasteboard.general.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        let pasteboard = NSPasteboard.general

        // Check for transient/concealed types (password managers, etc.)
        if let types = pasteboard.types {
            let typeStrings = Set(types.map(\.rawValue))
            if !typeStrings.isDisjoint(with: Self.transientTypes) {
                return // Skip sensitive clipboard content
            }
        }

        // Get source app bundle ID
        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        var didInsert = false

        // Try file URL (Finder copy)
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], !urls.isEmpty {
            for url in urls where url.isFileURL {
                let _ = rc_clipboard_insert_file(url.path, sourceApp)
            }
            didInsert = true
        }

        // Try to read text content
        else if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let _ = rc_clipboard_insert_text(text, sourceApp)
            didInsert = true
        }

        // Try to read image content (PNG)
        else if let imageData = pasteboard.data(forType: .png) {
            imageData.withUnsafeBytes { buffer in
                guard let ptr = buffer.baseAddress?.assumingMemoryBound(to: UInt8.self) else { return }
                let _ = rc_clipboard_insert_image(ptr, UInt64(imageData.count), 0, 0, sourceApp)
            }
            didInsert = true
        }

        // Try TIFF (screenshots are often TIFF)
        else if let tiffData = pasteboard.data(forType: .tiff),
           let bitmap = NSBitmapImageRep(data: tiffData),
           let pngData = bitmap.representation(using: .png, properties: [:]) {
            pngData.withUnsafeBytes { buffer in
                guard let ptr = buffer.baseAddress?.assumingMemoryBound(to: UInt8.self) else { return }
                let width = UInt32(bitmap.pixelsWide)
                let height = UInt32(bitmap.pixelsHigh)
                let _ = rc_clipboard_insert_image(ptr, UInt64(pngData.count), width, height, sourceApp)
            }
            didInsert = true
        }

        if didInsert {
            onClipboardChanged?()
        }
    }
}
